### ISSUE TITLE
Got error accessing to admin.

### ISSUE THREAD

**Issue by rikusen0335** [W3Layouts/delog#15]
When I access to admin, the page say

```
Error loading the CMS configuration
Config Errors:
'collections[1].fields[1].pattern' should NOT have fewer than 2 items
Check your config.yml file.
```

Am I wrong with configurations? I think I set everything in readme.

**Comment by RanjithNair** [comment]
@rikusen0335  You will have to change [this line](https://github.com/W3Layouts/gatsby-starter-delog/blob/master/static/admin/config.yml#L59) in the config.yml file to the below one :-

`pattern: [/, 'Path must start with /']`

**Comment by rikusen0335** [comment]
This fixed issue! Thanks a lot.
But why this fix the issue?
