### ISSUE TITLE
Example site is down

### ISSUE THREAD

**Issue by segheysens** [W3Layouts/delog#26]
Hi, I came across this template from [Netlify's Templates page](https://templates.netlify.com/template/delog-gatsby-netlifycms/) and was hoping to interact with [the example site](https://delog-w3layouts.netlify.app/), but it appears the app was taken down. Could you republish it and submit a new link to Netlify?

**Comment by talmax1124** [comment]
Can you check again? It is currently running

**Comment by segheysens** [comment]
@talmax1124 yep, looks good. Thank you!
